apiVersion: v1
kind: Service
metadata:  
  name: load-balancer-service-two
spec:
  selector:
    app: nginx-test-two
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
